name: Deploy CentOS 9 on GCP with Terraform & Ansible

on:
  workflow_dispatch:

env:
  TF_VAR_project_id:      "ansi-465711"
  TF_VAR_credentials_file: "/home/shruti/ansi-terra/actions-runner/_work/ansibleterraformpieline-/ansibleterraformpieline-/terraform-ansible/sa.json"
  ANSIBLE_HOST_KEY_CHECKING: "False"

jobs:
  deploy:
    runs-on: self-hosted   # or ubuntu-latest if you install tools
    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # --- 1. Terraform ---
      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Export public IP
        id: ip
        run: |
          echo "ip=$(terraform output -raw public_ip)" >> $GITHUB_OUTPUT
          echo "IP=${{ steps.ip.outputs.ip }}" >> $GITHUB_ENV

      # --- 2. Build Ansible inventory ---
      - name: Create inventory
        working-directory: ansible
        run: |
          cat > inventory <<EOF
          [centos9]
          ${{ steps.ip.outputs.ip }} ansible_user=centos ansible_ssh_private_key_file=~/.ssh/id_rsa
          EOF

      # --- 3. Ansible ---
      - name: Run Ansible
        working-directory: ansible
        run: |
          ansible-playbook -i inventory playbook.yml
