
name: 'Install Terraform'

on:
  workflow_dispatch:
  
#on:
#  push:
#    branches: [ "main" ]
#  pull_request:

permissions:
  contents: read

jobs:
  terraform:
    name: 'Terraform'
    runs-on: self-hosted
    environment: production

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Install required packages
      run: |
        sudo dnf install -y yum-utils

    - name: Add HashiCorp YUM repo
      run: |
        sudo dnf config-manager --add-repo https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo

    - name: Install Terraform
      run: |
        sudo dnf install -y terraform
        terraform version
